# seamsh - Copyright (C) <2010-2020>
# <Universite catholique de Louvain (UCL), Belgium
# 	
# List of the contributors to the development of seamsh: see AUTHORS file.
# Description and complete License: see LICENSE file.
# 	
# This program (seamsh) is free software: 
# you can redistribute it and/or modify it under the terms of the GNU Lesser General 
# Public License as published by the Free Software Foundation, either version
# 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this program (see COPYING file).  If not, 
# see <http://www.gnu.org/licenses/>.

seamshbuild-linux :
  image : immc/seamsh-build:v0.9
  stage : build
  script:
    - python3 setup.py sdist
    - python3 setup.py bdist_wheel --plat-name=manylinux1_x86_64
  artifacts:
    paths:
      - dist
    expire_in: 1 day

seamshbuild-windows :
  image : immc/seamsh-build:v0.9
  stage : build
  script:
    - LDSHARED="x86_64-w64-mingw32-gcc" LDFLAGS="-shared -O2" CC=x86_64-w64-mingw32-gcc CFLAGS="-O2 -fno-stack-protector" python3 setup.py bdist_wheel --plat-name=win_amd64

  artifacts:
    paths:
      - dist
    expire_in: 1 day

seamshbuild-osx :
  image : immc/seamsh-build:v0.9
  stage : build
  script:
    - $(osxcross-conf) & LDSHARED="o64-clang" LDFLAGS="-O2 -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names" CC=o64-clang python3 setup.py bdist_wheel --plat-name=macosx_10_9_x86_64
  artifacts:
    paths:
      - dist
    expire_in: 1 day

seamshtest :
  image : immc/seamsh-valid:v0.4
  stage : test
  script:
    - pip3 install --user dist/*manylinux1_x86_64*
    - cd tests
    - python3 testshp.py 

seamshtest-py36 :
  image : immc/seamsh-valid-py36:v0.1
  stage : test
  script:
    - pip3 install --user dist/*manylinux1_x86_64*
    - export PYTHONPATH=$HOME/.local/lib/python3/dist-packages/gmsh-git-Linux64-sdk/lib/:$PYTHONPATH
    - cd tests
    - python3 testshp.py 

pages:
  image : immc/seamsh-build:v0.9
  stage : deploy
  script:
    - pip3 install --user dist/*manylinux1_x86_64*
    - cd doc
    - python3 gen_examples.py
    - make html
    - mv _build/html ../public
  artifacts:
    paths:
      - public
    expire_in: 1 day


seamshdeploy-test :
  image : immc/seamsh-build:v0.9
  stage : deploy
  rules :
    - if: '$CI_COMMIT_TAG =~ /^w-.*$/'
      when: always
  script:
    - twine upload --repository testpypi dist/* 


seamshdeploy :
  image : immc/seamsh-build:v0.9
  stage : deploy
  rules :
    - if: '$CI_COMMIT_TAG =~ /^v-.*$/'
      when: always
  script:
    - twine upload dist/* 
